Convert to new-build Travis job
This builds & tests from within the extracted src-tarball,
so from here on we need to keep `cabal sdist` working.

The GHC 7.6 build is allowed to fail as for some reason the
HighLevelTest fails always on Travis.

This disables --dependencies-only temporarily until
https://github.com/haskell/cabal/issues/3490 is addressed

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,34 +1,80 @@
-# NB: don't set `language: haskell` here
+# This file has been generated by `make_travis_yml_2.hs`
+# see https://github.com/hvr/multi-ghc-travis for more information
+language: c
+sudo: false
 
-# See also https://github.com/hvr/multi-ghc-travis for more information
+cache:
+  directories:
+    - $HOME/.cabal/packages
+    - $HOME/.cabal/store
 
-# The following lines enable several GHC versions and/or HP versions
-# to be tested; often it's enough to test only against the last
-# release of a major GHC version. Setting HPVER implictly sets
-# GHCVER. Omit lines with versions you don't need/want testing for.
-env:
- - GHCVER=7.6.3
- - GHCVER=7.8.3
- - GHCVER=7.10.3
+before_cache:
+  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/build-reports.log
+  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/00-index.tar
 
 notifications:
   email: false
   irc: "chat.freenode.net#hackage"
 
+matrix:
+  include:
+    - env: CABALVER=1.24 GHCVER=7.6.3
+      compiler: ": #GHC 7.6.3"
+      addons: {apt: {packages: [cabal-install-1.24,ghc-7.6.3,alex-3.1.7,happy-1.19.5], sources: [hvr-ghc]}}
+    - env: CABALVER=1.24 GHCVER=7.8.4
+      compiler: ": #GHC 7.8.4"
+      addons: {apt: {packages: [cabal-install-1.24,ghc-7.8.4,alex-3.1.7,happy-1.19.5], sources: [hvr-ghc]}}
+    - env: CABALVER=1.24 GHCVER=7.10.3
+      compiler: ": #GHC 7.10.3"
+      addons: {apt: {packages: [cabal-install-1.24,ghc-7.10.3,alex-3.1.7,happy-1.19.5], sources: [hvr-ghc]}}
+
+  allow_failures:
+    # HighLevelTest fails to startup the server for some reason
+    - env: CABALVER=1.24 GHCVER=7.6.3
+
 before_install:
- - sudo add-apt-repository -y ppa:hvr/ghc
- - sudo apt-get update
- - sudo apt-get install cabal-install-1.22 ghc-$GHCVER libicu-dev happy-1.19.5 alex-3.1.7
- - export PATH=/opt/cabal/1.22/bin:/opt/ghc/$GHCVER/bin:/opt/happy/1.19.5/bin:/opt/alex/3.1.7/bin:$PATH
+ - unset CC
+ - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:/opt/happy/1.19.5/bin:/opt/alex/3.1.7/bin:$PATH
 
 install:
-  - cabal update
-  - cabal sandbox init
-  - cabal install --only-dependencies -j4 --enable-tests --disable-optimization --force-reinstalls --ghc-options=-w
+ - cabal --version
+ - BENCH=${BENCH---enable-benchmarks}
+ - TEST=${TEST---enable-tests}
+ - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
+ - if [ -f $HOME/.cabal/packages/hackage.haskell.org/00-index.tar.gz ];
+   then
+     zcat $HOME/.cabal/packages/hackage.haskell.org/00-index.tar.gz >
+          $HOME/.cabal/packages/hackage.haskell.org/00-index.tar;
+   fi
+ - travis_retry cabal update -v
+ - sed -i 's/^jobs:.*$/jobs:2/' ${HOME}/.cabal/config
+ # install build-dependencies before script-phase
+ - if [ -f configure.ac ]; then autoreconf -i; fi
+ # temporarily disabled since --dep doesn't work yet, see https://github.com/haskell/cabal/issues/3490
+ # - cabal new-build ${TEST} ${BENCH} --dep
+ # - rm -rf dist-newstyle/
 
+# Here starts the actual work to be performed for the package under test;
+# any command which exits with a non-zero exit code causes the build to fail.
 script:
- - cabal configure --enable-tests --disable-optimization
- - cabal build -j1
- - cabal test --show-details=streaming
+ # test that a source-distribution can be generated
+ - cabal sdist
+
+ # extract the source-distribution and chdir into it
+ - SRC_BASENAME=$(cabal info . | awk '{print $2;exit}')
+ - tar -C dist/ -xf dist/$SRC_BASENAME.tar.gz
+ - "echo 'packages: .' > dist/$SRC_BASENAME/cabal.project"
+ - cd dist/$SRC_BASENAME/
+
+ ## from here on, CWD is inside the extracted source-tarball
+ ## Check that the resulting source distribution can be built w/o and w/ tests
+ ## first pass, w/o tests
+ - cabal new-build --disable-tests --disable-benchmarks -v2
+ ## and now with tests & benchmarks
+ - cabal new-build ${TEST} ${BENCH} -v2
+
+ # there's no 'cabal new-test' yet, so call tests directly for now
+ - T=PackageTests;  ./dist-newstyle/build/*/build/$T/$T --plain
+ - T=HighLevelTest; ./dist-newstyle/build/*/build/$T/$T
 
 # EOF
